export const APP_CONSTANTS = {
    PAGINATION_DEFAULT_LIMIT: 20,
    PAGINATION_MAX_LIMIT: 100,
    MAX_RESUME_SIZE_BYTES: 5 * 1024 * 1024, // 5MB
    AUDIT_ACTIONS: {
        LOGIN: 'LOGIN',
        LOGOUT: 'LOGOUT',
        TENANT_CREATE: 'TENANT_CREATE',
        TENANT_UPDATE: 'TENANT_UPDATE',
        USER_CREATE: 'USER_CREATE',
        COMPANY_CREATE: 'COMPANY_CREATE',
        DRIVE_CREATE: 'DRIVE_CREATE',
        DRIVE_UPDATE: 'DRIVE_UPDATE',
        APPLICATION_CREATE: 'APPLICATION_CREATE',
        STAGE_UPDATE: 'STAGE_UPDATE',
        STUDENT_UPDATE: 'STUDENT_UPDATE',
        ANNOUNCEMENT_CREATE: 'ANNOUNCEMENT_CREATE',
        CREDENTIAL_GENERATE: 'CREDENTIAL_GENERATE',
        DRIVE_DELETE: 'DRIVE_DELETE',
        DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
        DEPARTMENT_DELETE: 'DEPARTMENT_DELETE',
    },
} as const;
